### PR TITLE
Improvements for CS course

### PR DESCRIPTION
**Pull request by moy**
Hi,

I'm a new colleague of @lauregonnord. Thanks for your work on this project!

I've made a few modifications to the simulator and assembler, some of which will be needed for the course. Can you have a look at the modifications and merge them?

Thanks,

### CODE REVIEW

**Comment by poechsel** [comment]
Is it a problem if I merge / do the modifications on monday ? 
I also have a proposition: instead of having a refresh / print instruction we could add a more global "syscall" instruction. A syscall would be a call to a C function, thus enabling us to hack something to deal with input, have several print function (a printint, printchar, ...). It could be use liked `syscall n` (where n corresponds to a function, for exemple refresh, print). The arguments would be taken on the stack. It could also be put under opcode "0b1110xxx" (which was reserved for future use). What do you think ?

**Comment by moy** [comment]
> Is it a problem if I merge / do the modifications on monday ?

Nothing urgent, it can wait until Monday. But I see that you just merged them actually ;-).

> I also have a proposition: instead of having a refresh / print instruction we could add a more global "syscall" instruction.

I'm a bit reluctant to doing that. Print is already not very realistic (it's typically a library, not an opcode). A syscall opcode that calls the host libc is a nice simulation tool, but it takes us one step away from the real CPU (I mean, the silicon if it existed, not the simulator).

`print` is really needed (as an opcode or as a library function) to be able to do any serious tests. Other syscalls can be fun, but are not _needed_ IMHO.

**Comment by poechsel** [comment]
Understood for the syscall!

I was wanting to do something like in X86 actually (with int 0x80). But because we don't have interruptions I just thought adding a syscall instruction would work. But you have a really good point!

**Comment by moy** [comment]
The real processor could have a syscall opcode, but that would be to call a function running on the processor, not calling the host in simulation.

Anyway, thanks for your work and thanks for merging!

**Pull request merged**
